name: minikube-test
on:
  - workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build and deploy to minikube
    env:
      REPO_NAME: minkube-local
      APP_NAME: nginx-test
      TAG: '0.0.1'
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Build image
      run: |
        cd ${GITHUB_WORKSPACE}
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env) 
        docker build -f ./Dockerfile -t ${{env.REPO_NAME}}/${{env.APP_NAME}}:${{env.TAG}} .
        echo -n "verifying images:"
        docker images        
    - name: Deploy to minikube
      run: |
        cd ${GITHUB_WORKSPACE}/.helm
        helm upgrade --install -f custom-values.yaml ${{env.APP_NAME}} ./chart
    - name: Wait untill pods are going to be ready
      run: |
        kubectl rollout status deployment/${{env.APP_NAME}} --timeout=5m
    - name: Test service URLs
      run: |
        minikube service list
        minikube service example --url
        echo "------------------opening the service------------------"
        curl $(minikube service example --url)  