name: run-demo
on:
  workflow_dispatch:
    inputs:
      use-sqlite:
        type: boolean
        description: USE_SQLITE
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build and deploy to minikube
    env:
      REPO_NAME: minkube-local
      APP_NAME: nginx-test
      TAG: '0.0.1'
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@v0.0.14
    - name: Build image
      run: |
        cd ${GITHUB_WORKSPACE}
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env) 
        docker build -f ./Dockerfile -t ${{env.REPO_NAME}}/${{env.APP_NAME}}:${{env.TAG}} .
        echo -n "verifying images:"
        docker images        
    - name: Deploy to minikube
      run: |
        cd ${GITHUB_WORKSPACE}/.helm
        helm upgrade --install --debug ${{env.APP_NAME}} ./chart --set image.repository=${{env.REPO_NAME}}/${{env.APP_NAME}} --set image.tag=${{env.TAG}} --set image.pullPolicy=Never --set service.type=NodePort --set-string env.sqliteEnabled=${{inputs.use-sqlite}}
    - name: Wait untill pods are going to be ready
      run: |
        kubectl rollout status deployment/${{env.APP_NAME}} --timeout=5m
    - name: Test service URLs
      run: |
        sudo apt-get install -y curl
        minikube service list
        minikube service ${{env.APP_NAME}} --url
        URL=$(minikube service ${{env.APP_NAME}} --url)
        echo "------------------Testing the service------------------"
        curl -v $URL